<?php
// /migrantcare/functions.php

// --- TRANSLATION DATA ---
$translations = [
  'en' => [
    'language' => 'English',
    'selectLanguage' => 'Select Your Language',
    'loginTitle' => 'MigrantCare Login',
    'mobilePlaceholder' => '10-digit mobile number',
    'pinPlaceholder' => '4-digit PIN',
    'loginButton' => 'Login',
    'registerPrompt' => "Don't have an account? Register",
    'createAccountTitle' => 'Create Account',
    'enterMobileLabel' => 'Enter Mobile Number',
    'sendOTPButton' => 'Send OTP',
    'verifyOTPTitle' => 'Verify OTP',
    'otpSentMessage' => 'An OTP has been sent to',
    'otpHint' => "(Hint: it's 123456)",
    'otpPlaceholder' => '6-digit OTP',
    'verifyOTPButton' => 'Verify OTP',
    'setPinTitle' => 'Set Your PIN',
    'createPinLabel' => 'Create a 4-Digit PIN',
    'confirmPinLabel' => 'Confirm PIN',
    'createAccountButton' => 'Create Account',
    'alreadyHaveAccount' => 'Already have an account? Login',
    'selectRoleTitle' => 'Select Your Role',
    'roleSelectionSubtitle' => 'Please choose how you will use this app.',
    'workerRole' => 'I am a Worker',
    'workerDescription' => 'Access your health records and find care.',
    'doctorRole' => 'I am a Doctor',
    'doctorDescription' => 'Manage patient records and view health data.',
    'welcomeMessage' => 'Welcome,',
    'logout' => 'Logout',
    'yourHealthID' => 'Your Digital Health ID',
    'showQRCode' => 'Show this QR code to any doctor or clinic.',
    'viewMyHistory' => 'View My Health History',
    'findHospital' => 'Find a Hospital',
    'healthAlerts' => 'Health Alerts & Info',
    'patientLookup' => 'Patient Lookup',
    'enterWorkerID' => 'Enter Worker ID from QR Code',
    'scanQRCode' => 'Scan QR Code',
    'viewPatientRecord' => 'View Patient Record',
    'publicHealthTitle' => 'Public Health Intelligence',
    'publicHealthDescription' => 'View real-time disease surveillance data for Tamil Nadu.',
    'viewDashboard' => 'View Dashboard',
    'backToDashboard' => '< Back to Dashboard',
    'workerProfileSetup' => 'Worker Profile Setup',
    'fullNameLabel' => 'Full Name',
    'ageLabel' => 'Age',
    'homeStateLabel' => 'Home State',
    'phoneNumberLabel' => 'Phone Number',
    'emergencyContactLabel' => 'Emergency Contact (Optional)',
    'currentLocationLabel' => 'Current Location',
    'getLocationButton' => 'Get Location',
    'proceedToVerification' => 'Proceed to Verification',
    'changeLanguage' => 'Change Language',
    'labReports' => 'Lab Reports',
    'testDate' => 'Test Date:',
    'at' => 'at',
    'doctorsNotes' => "Doctor's Notes:",
    'viewReport' => 'View Report',
    'healthProfileSetupTitle' => 'Complete Your Health Profile',
    'healthProfileSetupSubtitle' => 'This optional step helps doctors provide better care.',
    'heightLabel' => 'Height (in cm)',
    'weightLabel' => 'Weight (in kg)',
    'bloodGroupLabel' => 'Blood Group',
    'allergiesLabel' => 'Do you have any allergies? (If yes, specify)',
    'smokingLabel' => 'Do you smoke?',
    'chronicDiseasesLabel' => 'List any past or chronic diseases',
    'yesOption' => 'Yes',
    'noOption' => 'No',
    'preferNotToSayOption' => 'Prefer not to say',
    'saveProfileButton' => 'Save Profile',
    'skipButton' => 'Skip for Now',
    'myHealthProfile' => 'My Health Profile',
    'prescriptionReminders' => 'Prescription Reminders',
    'takeYourMedicineFor' => 'Take your medicine for',
    'prescribedByOn' => 'Prescribed by',
    'searchBySymptom' => 'Search by symptom or disease...',
    'hotspotWarning' => 'High Alert: This is currently an active hotspot in your area.',
    'overviewTab' => 'Overview',
    'consultationsTab' => 'Consultations',
    'vaccinesTab' => 'Vaccines',
    'symptomChecker' => 'AI Assistant',
    'firstAidGuide' => 'First Aid Guide',
    'financialAid' => 'Financial Aid',
    'linkESICard' => 'Link ESI Card',
    'checkSymptoms' => 'Check Symptoms',
    'possibleConditions' => 'Possible Conditions based on your symptoms',
    'selectSymptoms' => 'Select your symptoms',
    'esiNumber' => 'ESI Card Number',
    'linkCard' => 'Link Card',
    'esiLinked' => 'ESI Card Linked',
    'aiWelcomeMessage' => 'Hello! I am your health assistant. How are you feeling today? Describe your symptoms below.',
    'typeSymptomsHere' => 'Type your symptoms here...',
    'mentalHealthScreening' => 'Mental Health Screening',
    'consentForms' => 'Consent Forms',
    'referPatient' => 'Refer Patient',
    'startLiveChat' => 'Start Live Chat',
    'digitalConsent' => 'Digital Consent',
    'consentStatus' => 'Status',
    'consentPending' => 'Pending your approval',
    'consentGiven' => 'Approved',
    'approveConsent' => 'I Agree & Give Consent',
    'consentInfo' => 'Dr. Priya Sharma is requesting access to your full health history for consultation purposes.',
    'referralTitle' => 'Refer Patient to Specialist',
    'selectSpecialist' => 'Select Specialist',
    'referralNotes' => 'Notes for Specialist',
    'submitReferral' => 'Submit Referral',
    'liveConsultation' => 'Live Consultation',
    'patientLanguage' => "Patient's Language",
    'typeYourMessage' => 'Type your message here...',
    'mentalHealthTitle' => 'Mental Health Check-in',
    'mentalHealthSubtitle' => 'Your answers are confidential. This helps us understand your well-being.',
    'submitAnswers' => 'Submit Answers',
    'scoreInfo' => 'Your screening score is',
    'scoreLow' => 'This score is in a healthy range. Keep taking care of yourself!',
    'scoreMedium' => 'This score suggests you might be experiencing some emotional challenges. It could be helpful to talk to someone. Consider reaching out to a local health clinic.',
    'scoreHigh' => 'This score indicates you may be facing significant emotional distress. It is highly recommended you speak with a doctor or a mental health professional soon.',
    'rewardsTitle' => 'My Rewards',
    'yourPoints' => 'Your Points',
    'referFriend' => 'Refer a Friend',
    'howToEarn' => 'How to Earn Points',
    'earnCheckup' => 'Complete a health checkup: +50 Points',
    'earnReferral' => 'Refer another worker who registers: +100 Points',
    'redeemPoints' => 'Redeem Points for discounts on future consultations.',
    'esiStatus' => 'ESI Status',
    'esiLinkedTag' => 'Linked',
    'esiNotLinkedTag' => 'Not Linked',
    'scanningTitle' => 'Scanning QR Code...',
    'scanningSubtitle' => 'Please hold the QR code steady.',
    'treatedPatients' => 'Patients Treated',
    'dengueFever' => 'Dengue Fever',
    'dengueDetails' => 'Dengue is a viral infection caused by the dengue virus (DENV), transmitted to humans through the bite of infected mosquitoes.',
    'denguePrecautions' => 'Avoid mosquito bites. Remove stagnant water. Wear long sleeves. Rest and drink plenty of fluids like ORS.',
    'denguePrescription' => 'For fever, take Paracetamol ONLY. AVOID Aspirin or Ibuprofen. Consult a doctor immediately.',
    'malaria' => 'Malaria',
    'malariaDetails' => 'Malaria is a life-threatening disease caused by parasites that are transmitted to people through the bites of infected female Anopheles mosquitoes.',
    'malariaPrecautions' => 'Always sleep under a mosquito net. Use mosquito repellent. See a doctor for a blood test if you have fever with chills.',
    'malariaPrescription' => "Requires specific anti-malarial drugs after a doctor's consultation. Do not self-medicate.",
    'typhoid' => 'Typhoid Fever',
    'typhoidDetails' => 'Typhoid fever is a serious bacterial infection that easily spreads through contaminated food, water, and close contact.',
    'typhoidPrecautions' => 'Drink only boiled or bottled water. Eat well-cooked food. Wash hands frequently.',
    'typhoidPrescription' => 'Requires a course of antibiotics prescribed by a doctor. Complete the full course.',
  ],
'ta' => [
    'language' => 'தமிழ்',
    'selectLanguage' => 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    'loginTitle' => 'MigrantCare உள்நுழைவு',
    'mobilePlaceholder' => '10-இலக்க மொபைல் எண்',
    'pinPlaceholder' => '4-இலக்க பின்',
    'loginButton' => 'உள்நுழைக',
    'registerPrompt' => 'கணக்கு இல்லையா? பதிவு செய்க',
    'createAccountTitle' => 'புதிய கணக்கு உருவாக்கு',
    'enterMobileLabel' => 'மொபைல் எண்ணை உள்ளிடவும்',
    'sendOTPButton' => 'OTP அனுப்பு',
    'verifyOTPTitle' => 'OTP ஐ சரிபார்க்கவும்',
    'otpSentMessage' => 'க்கு ஒரு OTP அனுப்பப்பட்டது',
    'otpHint' => '(குறிப்பு: 123456)',
    'otpPlaceholder' => '6-இலக்க OTP',
    'verifyOTPButton' => 'OTP ஐ சரிபார்க்கவும்',
    'setPinTitle' => 'உங்கள் பின்னை அமைக்கவும்',
    'createPinLabel' => '4-இலக்க பின்னை உருவாக்கவும்',
    'confirmPinLabel' => 'பின்னை உறுதிப்படுத்தவும்',
    'createAccountButton' => 'கணக்கை உருவாக்கு',
    'alreadyHaveAccount' => 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
    'selectRoleTitle' => 'உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',
    'roleSelectionSubtitle' => 'இந்த செயலியை எவ்வாறு பயன்படுத்துவீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்.',
    'workerRole' => 'நான் ஒரு தொழிலாளி',
    'workerDescription' => 'உங்கள் சுகாதார பதிவுகளை அணுகவும் மற்றும் கவனிப்பைப் பெறவும்.',
    'doctorRole' => 'நான் ஒரு மருத்துவர்',
    'doctorDescription' => 'நோயாளியின் பதிவுகளை நிர்வகிக்கவும் மற்றும் சுகாதார தரவைப் பார்க்கவும்.',
    'welcomeMessage' => 'வரவேற்கிறோம்,',
    'logout' => 'வெளியேறு',
    'yourHealthID' => 'உங்கள் டிஜிட்டல் சுகாதார ஐடி',
    'showQRCode' => 'இந்த QR குறியீட்டை எந்த மருத்துவர் அல்லது மருத்துவமனைக்கும் காட்டவும்.',
    'viewMyHistory' => 'எனது சுகாதார வரலாற்றைக் காண்க',
    'findHospital' => 'ஒரு மருத்துவமனையைக் கண்டுபிடி',
    'healthAlerts' => 'சுகாதார எச்சரிக்கைகள் மற்றும் தகவல்',
    'patientLookup' => 'நோயாளி தேடல்',
    'enterWorkerID' => 'QR குறியீட்டிலிருந்து தொழிலாளர் ஐடியை உள்ளிடவும்',
    'scanQRCode' => 'QR குறியீட்டை ஸ்கேன் செய்யவும்',
    'viewPatientRecord' => 'நோயாளியின் பதிவைக் காண்க',
    'publicHealthTitle' => 'பொது சுகாதார நுண்ணறிவு',
    'publicHealthDescription' => 'தமிழ்நாட்டிற்கான நிகழ்நேர நோய் கண்காணிப்புத் தரவைக் காண்க.',
    'viewDashboard' => 'டாஷ்போர்டைக் காண்க',
    'backToDashboard' => '< டாஷ்போர்டுக்குத் திரும்பு',
    'workerProfileSetup' => 'தொழிலாளர் சுயவிவர அமைப்பு',
    'fullNameLabel' => 'முழு பெயர்',
    'ageLabel' => 'வயது',
    'homeStateLabel' => 'சொந்த மாநிலம்',
    'phoneNumberLabel' => 'தொலைபேசி எண்',
    'emergencyContactLabel' => 'அவசர தொடர்பு (விரும்பினால்)',
    'currentLocationLabel' => 'தற்போதைய இடம்',
    'getLocationButton' => 'இருப்பிடத்தைப் பெறு',
    'proceedToVerification' => 'சரிபார்ப்புக்குச் செல்லவும்',
    'changeLanguage' => 'மொழியை மாற்று',
    'labReports' => 'ஆய்வக அறிக்கைகள்',
    'testDate' => 'தேதி:',
    'at' => 'இல்',
    'doctorsNotes' => 'மருத்துவரின் குறிப்புகள்:',
    'viewReport' => 'அறிக்கையைக் காண்க',
    'healthProfileSetupTitle' => 'உங்கள் சுகாதார சுயவிவரத்தை முடிக்கவும்',
    'healthProfileSetupSubtitle' => 'இந்த விருப்பப்படி படி மருத்துவர்களுக்கு சிறந்த கவனிப்பை வழங்க உதவுகிறது.',
    'heightLabel' => 'உயரம் (செ.மீ)',
    'weightLabel' => 'எடை (கிலோ)',
    'bloodGroupLabel' => 'இரத்த வகை',
    'allergiesLabel' => 'உங்களுக்கு ஏதேனும் ஒவ்வாமை உள்ளதா? (ஆம் எனில், குறிப்பிடவும்)',
    'smokingLabel' => 'நீங்கள் புகைப்பிடிப்பீர்களா?',
    'chronicDiseasesLabel' => 'கடந்த கால அல்லது நாள்பட்ட நோய்களை பட்டியலிடுங்கள்',
    'yesOption' => 'ஆம்',
    'noOption' => 'இல்லை',
    'preferNotToSayOption' => 'சொல்ல விரும்பவில்லை',
    'saveProfileButton' => 'சுயவிவரத்தை சேமி',
    'skipButton' => 'இப்போதைக்கு தவிர்',
    'myHealthProfile' => 'எனது சுகாதார சுயவிவரம்',
    'prescriptionReminders' => 'மருந்துச் சீட்டு நினைவூட்டல்கள்',
    'takeYourMedicineFor' => 'இதற்கு உங்கள் மருந்தை எடுத்துக் கொள்ளுங்கள்',
    'prescribedByOn' => 'பரிந்துரைத்தவர்',
    'searchBySymptom' => 'அறிகுறி அல்லது நோய் மூலம் தேடவும்...',
    'hotspotWarning' => 'உயர் எச்சரிக்கை: இது தற்போது உங்கள் பகுதியில் செயலில் உள்ள ஹாட்ஸ்பாட் ஆகும்.',
    'overviewTab' => 'கண்ணோட்டம்',
    'consultationsTab' => 'ஆலோசனைகள்',
    'vaccinesTab' => 'தடுப்பூசிகள்',
    'symptomChecker' => 'AI உதவியாளர்',
    'firstAidGuide' => 'முதலுதவி வழிகாட்டி',
    'financialAid' => 'நிதி உதவி',
    'linkESICard' => 'ESI கார்டை இணைக்கவும்',
    'checkSymptoms' => 'அறிகுறைகளை சரிபார்க்கவும்',
    'possibleConditions' => 'உங்கள் அறிகுறிகளின் அடிப்படையில் சாத்தியமான நோய்கள்',
    'selectSymptoms' => 'உங்கள் அறிகுறிகளைத் தேர்ந்தெடுக்கவும்',
    'esiNumber' => 'ESI அட்டை எண்',
    'linkCard' => 'கார்டை இணைக்கவும்',
    'esiLinked' => 'ESI கார்டு இணைக்கப்பட்டது',
    'aiWelcomeMessage' => 'வணக்கம்! நான் உங்கள் சுகாதார உதவியாளர். இன்று நீங்கள் எப்படி உணர்கிறீர்கள்? உங்கள் அறிகுறிகளை கீழே விவரிக்கவும்.',
    'typeSymptomsHere' => 'உங்கள் அறிகுறிகளை இங்கே தட்டச்சு செய்க...',
    'mentalHealthScreening' => 'மனநல பரிசோதனை',
    'consentForms' => 'சம்மதப் படிவங்கள்',
    'referPatient' => 'நோயாளியை giới thiệu செய்யவும்',
    'startLiveChat' => 'நேரடி அரட்டையைத் தொடங்கு',
    'digitalConsent' => 'டிஜிட்டல் சம்மதம்',
    'consentStatus' => 'நிலை',
    'consentPending' => 'உங்கள் ஒப்புதலுக்காக காத்திருக்கிறது',
    'consentGiven' => 'ஒப்புதல் அளிக்கப்பட்டது',
    'approveConsent' => 'நான் ஒப்புக்கொண்டு சம்மதம் தெரிவிக்கிறேன்',
    'consentInfo' => 'மருத்துவர் பிரியா சர்மா ஆலோசனை நோக்கங்களுக்காக உங்கள் முழு சுகாதார வரலாற்றையும் அணுகக் கோருகிறார்.',
    'referralTitle' => 'நோயாளியை நிபுணரிடம் giới thiệu செய்யவும்',
    'selectSpecialist' => 'நிபுணரைத் தேர்ந்தெடுக்கவும்',
    'referralNotes' => 'நிபுணருக்கான குறிப்புகள்',
    'submitReferral' => 'பரிந்துரையைச் சமர்ப்பி',
    'liveConsultation' => 'நேரடி ஆலோசனை',
    'patientLanguage' => 'நோயாளியின் மொழி',
    'typeYourMessage' => 'உங்கள் செய்தியை இங்கே தட்டச்சு செய்க...',
    'mentalHealthTitle' => 'மனநலப் பரிசோதனை',
    'mentalHealthSubtitle' => 'உங்கள் பதில்கள் ரகசியமானவை. இது உங்கள் நல்வாழ்வைப் புரிந்துகொள்ள எங்களுக்கு உதவுகிறது.',
    'submitAnswers' => 'பதில்களைச் சமர்ப்பி',
    'scoreInfo' => 'உங்கள் ஸ்கிரீனிங் ஸ்கோர்',
    'scoreLow' => 'இந்த மதிப்பெண் ஆரோக்கியமான வரம்பில் உள்ளது. உங்களை நீங்களே கவனித்துக் கொள்ளுங்கள்!',
    'scoreMedium' => 'இந்த மதிப்பெண் நீங்கள் சில உணர்ச்சி சவால்களை சந்திக்க நேரிடலாம் என்று கூறுகிறது. யாரிடமாவது பேசுவது உதவியாக இருக்கும். உள்ளூர் சுகாதார கிளினிக்கைத் தொடர்புகொள்வதைக் கவனியுங்கள்.',
    'scoreHigh' => 'இந்த மதிப்பெண் நீங்கள் குறிப்பிடத்தக்க உணர்ச்சி ரீதியான துன்பத்தை சந்திக்க நேரிடலாம் என்பதைக் குறிக்கிறது. விரைவில் ஒரு மருத்துவர் அல்லது மனநல நிபுணருடன் பேசுவது மிகவும் பரிந்துரைக்கப்படுகிறது.',
    'rewardsTitle' => 'எனது வெகுமதிகள்',
    'yourPoints' => 'உங்கள் புள்ளிகள்',
    'referFriend' => 'நண்பரைப் giới thiệu செய்யவும்',
    'howToEarn' => 'புள்ளிகளைப் பெறுவது எப்படி',
    'earnCheckup' => 'சுகாதாரப் பரிசோதனையை முடிக்கவும்: +50 புள்ளிகள்',
    'earnReferral' => 'பதிவு செய்யும் மற்றொரு தொழிலாளியைப் giới thiệu செய்யவும்: +100 புள்ளிகள்',
    'redeemPoints' => 'எதிர்கால ஆலோசனைகளில் தள்ளுபடிகளைப் பெற புள்ளிகளைப் பெறுங்கள்.',
    'esiStatus' => 'ESI நிலை',
    'esiLinkedTag' => 'இணைக்கப்பட்டது',
    'esiNotLinkedTag' => 'இணைக்கப்படவில்லை',
    'scanningTitle' => 'QR குறியீட்டை ஸ்கேன் செய்கிறது...',
    'scanningSubtitle' => 'தயவுசெய்து QR குறியீட்டை சீராகப் பிடிக்கவும்.',
    'treatedPatients' => 'சிகிச்சையளிக்கப்பட்ட நோயாளிகள்',
    'dengueFever' => 'டெங்கு காய்ச்சல்',
    'dengueDetails' => 'டெங்கு என்பது டெங்கு வைரஸால் (DENV) ஏற்படும் ஒரு வைரஸ் தொற்று ஆகும், இது பாதிக்கப்பட்ட கொசுக்களின் கடியால் மனிதர்களுக்குப் பரவுகிறது.',
    'denguePrecautions' => 'கொசுக்கடியைத் தவிர்க்கவும். தேங்கி நிற்கும் நீரை அகற்றவும். முழுக்கை ஆடைகளை அணியவும். ஓய்வெடுத்து ORS போன்ற திரவங்களை நிறைய குடிக்கவும்.',
    'denguePrescription' => 'காய்ச்சலுக்கு, பாராசிட்டமால் மட்டும் எடுத்துக் கொள்ளுங்கள். ஆஸ்பிரின் அல்லது இப்யூபுரூஃபனைத் தவிர்க்கவும். உடனடியாக மருத்துவரை அணுகவும்.',
    'malaria' => 'மலேரியா',
    'malariaDetails' => 'மலேரியா என்பது ஒட்டுண்ணிகளால் ஏற்படும் உயிருக்கு ஆபத்தான நோயாகும், இது பாதிக்கப்பட்ட பெண் அனோபிலிஸ் கொசுக்களின் கடியால் மனிதர்களுக்குப் பரவுகிறது.',
    'malariaPrecautions' => 'எப்போதும் கொசுவலைக்குள் தூங்கவும். கொசு விரட்டியைப் பயன்படுத்தவும். குளிர் காய்ச்சல் இருந்தால் இரத்தப் பரிசோதனைக்கு மருத்துவரைப் பார்க்கவும்.',
    'malariaPrescription' => 'மருத்துவரின் ஆலோசனைக்குப் பிறகு குறிப்பிட்ட மலேரியா எதிர்ப்பு மருந்துகள் தேவை. சுயமாக மருந்து உட்கொள்ள வேண்டாம்.',
    'typhoid' => 'டைபாய்டு காய்ச்சல்',
    'typhoidDetails' => 'டைபாய்டு காய்ச்சல் ஒரு கடுமையான பாக்டீரியா தொற்று ஆகும், இது அசுத்தமான உணவு, நீர் மற்றும் நெருங்கிய தொடர்பு மூலம் எளிதில் பரவுகிறது.',
    'typhoidPrecautions' => 'காய்ச்சிய அல்லது பாட்டில் நீரை மட்டுமே குடிக்கவும். நன்கு சமைத்த உணவை உண்ணுங்கள். அடிக்கடி கைகளைக் கழுவவும்.',
    'typhoidPrescription' => 'மருத்துவர் பரிந்துரைத்த நுண்ணுயிர் எதிர்ப்பிகளின் ஒரு படிப்பு தேவை. முழுப் படிப்பையும் முடிக்கவும்.',
  ],
  'hi' => [
    'language' => 'हिन्दी',
    'selectLanguage' => 'अपनी भाषा चुनें',
    'loginTitle' => 'माइग्रेंटकेयर लॉगिन',
    'mobilePlaceholder' => '10-अंकीय मोबाइल नंबर',
    'pinPlaceholder' => '4-अंकीय पिन',
    'loginButton' => 'लॉग इन करें',
    'registerPrompt' => 'खाता नहीं है? रजिस्टर करें',
    'createAccountTitle' => 'खाता बनाएं',
    'enterMobileLabel' => 'मोबाइल नंबर दर्ज करें',
    'sendOTPButton' => 'ओटीपी भेजें',
    'verifyOTPTitle' => 'ओटीपी सत्यापित करें',
    'otpSentMessage' => 'पर एक ओटीपी भेजा गया है',
    'otpHint' => '(संकेत: यह 123456 है)',
    'otpPlaceholder' => '6-अंकीय ओटीपी',
    'verifyOTPButton' => 'ओटीपी सत्यापित करें',
    'setPinTitle' => 'अपना पिन सेट करें',
    'createPinLabel' => '4-अंकीय पिन बनाएं',
    'confirmPinLabel' => 'पिन की पुष्टि करें',
    'createAccountButton' => 'खाता बनाएं',
    'alreadyHaveAccount' => 'पहले से ही एक खाता है? लॉग इन करें',
    'selectRoleTitle' => 'अपनी भूमिका चुनें',
    'roleSelectionSubtitle' => 'कृपया चुनें कि आप इस ऐप का उपयोग कैसे करेंगे।',
    'workerRole' => 'मैं एक कार्यकर्ता हूँ',
    'workerDescription' => 'अपने स्वास्थ्य रिकॉर्ड तक पहुँचें और देखभाल पाएँ।',
    'doctorRole' => 'मैं एक डॉक्टर हूँ',
    'doctorDescription' => 'रोगी रिकॉर्ड प्रबंधित करें और स्वास्थ्य डेटा देखें।',
    'welcomeMessage' => 'स्वागत है,',
    'logout' => 'लॉग आउट',
    'yourHealthID' => 'आपकी डिजिटल स्वास्थ्य आईडी',
    'showQRCode' => 'यह क्यूआर कोड किसी भी डॉक्टर या क्लिनिक को दिखाएं।',
    'viewMyHistory' => 'मेरा स्वास्थ्य इतिहास देखें',
    'findHospital' => 'एक अस्पताल खोजें',
    'healthAlerts' => 'स्वास्थ्य चेतावनी और जानकारी',
    'patientLookup' => 'रोगी खोज',
    'enterWorkerID' => 'क्यूआर कोड से कार्यकर्ता आईडी दर्ज करें',
    'scanQRCode' => 'क्यूआर कोड स्कैन करें',
    'viewPatientRecord' => 'रोगी रिकॉर्ड देखें',
    'publicHealthTitle' => 'सार्वजनिक स्वास्थ्य इंटेलिजेंस',
    'publicHealthDescription' => 'तमिलनाडु के लिए वास्तविक समय रोग निगरानी डेटा देखें।',
    'viewDashboard' => 'डैशबोर्ड देखें',
    'backToDashboard' => '< डैशबोर्ड पर वापस जाएं',
    'workerProfileSetup' => 'कार्यकर्ता प्रोफ़ाइल सेटअप',
    'fullNameLabel' => 'पूरा नाम',
    'ageLabel' => 'उम्र',
    'homeStateLabel' => 'गृह राज्य',
    'phoneNumberLabel' => 'फ़ोन नंबर',
    'emergencyContactLabel' => 'आपातकालीन संपर्क (वैकल्पिक)',
    'currentLocationLabel' => 'वर्तमान स्थान',
    'getLocationButton' => 'स्थान प्राप्त करें',
    'proceedToVerification' => 'सत्यापन के लिए आगे बढ़ें',
    'changeLanguage' => 'भाषा बदलें',
    'labReports' => 'लैब रिपोर्ट',
    'testDate' => 'परीक्षण तिथि:',
    'at' => 'पर',
    'doctorsNotes' => "डॉक्टर के नोट्स:",
    'viewReport' => 'रिपोर्ट देखें',
    'healthProfileSetupTitle' => 'अपनी स्वास्थ्य प्रोफ़ाइल पूरी करें',
    'healthProfileSetupSubtitle' => 'यह वैकल्पिक कदम डॉक्टरों को बेहतर देखभाल प्रदान करने में मदद करता है।',
    'heightLabel' => 'ऊंचाई (सेमी में)',
    'weightLabel' => 'वजन (किलो में)',
    'bloodGroupLabel' => 'रक्त समूह',
    'allergiesLabel' => 'क्या आपको कोई एलर्जी है? (यदि हाँ, तो निर्दिष्ट करें)',
    'smokingLabel' => 'क्या आप धूम्रपान करते हैं?',
    'chronicDiseasesLabel' => 'किसी भी पिछली या पुरानी बीमारियों की सूची बनाएं',
    'yesOption' => 'हाँ',
    'noOption' => 'नहीं',
    'preferNotToSayOption' => 'कहना पसंद नहीं है',
    'saveProfileButton' => 'प्रोफ़ाइल सहेजें',
    'skipButton' => 'अभी के लिए छोड़ें',
    'myHealthProfile' => 'मेरी स्वास्थ्य प्रोफ़ाइल',
    'prescriptionReminders' => 'प्रिस्क्रिप्शन अनुस्मारक',
    'takeYourMedicineFor' => 'इसके लिए अपनी दवा लें',
    'prescribedByOn' => 'द्वारा निर्धारित',
    'searchBySymptom' => 'लक्षण या बीमारी से खोजें...',
    'hotspotWarning' => 'उच्च चेतावनी: यह वर्तमान में आपके क्षेत्र में एक सक्रिय हॉटस्पॉट है।',
    'overviewTab' => 'अवलोकन',
    'consultationsTab' => 'परामर्श',
    'vaccinesTab' => 'टीके',
    'symptomChecker' => 'एआई सहायक',
    'firstAidGuide' => 'प्राथमिक चिकित्सा गाइड',
    'financialAid' => 'वित्तीय सहायता',
    'linkESICard' => 'ईएसआई कार्ड लिंक करें',
    'checkSymptoms' => 'लक्षणों की जाँच करें',
    'possibleConditions' => 'आपके लक्षणों के आधार पर संभावित स्थितियाँ',
    'selectSymptoms' => 'अपने लक्षण चुनें',
    'esiNumber' => 'ईएसआई कार्ड नंबर',
    'linkCard' => 'कार्ड लिंक करें',
    'esiLinked' => 'ईएसआई कार्ड लिंक किया गया',
    'aiWelcomeMessage' => 'नमस्ते! मैं आपका स्वास्थ्य सहायक हूं। आज आप कैसा महसूस कर रहे हैं? नीचे अपने लक्षण बताएं।',
    'typeSymptomsHere' => 'यहां अपने लक्षण टाइप करें...',
    'mentalHealthScreening' => 'मानसिक स्वास्थ्य जांच',
    'consentForms' => 'सहमति प्रपत्र',
    'referPatient' => 'रोगी को रेफर करें',
    'startLiveChat' => 'लाइव चैट शुरू करें',
    'digitalConsent' => 'डिजिटल सहमति',
    'consentStatus' => 'स्थिति',
    'consentPending' => 'आपकी मंजूरी लंबित है',
    'consentGiven' => 'स्वीकृत',
    'approveConsent' => 'मैं सहमत हूं और सहमति देता हूं',
    'consentInfo' => 'डॉ. प्रिया शर्मा परामर्श उद्देश्यों के लिए आपके पूरे स्वास्थ्य इतिहास तक पहुंच का अनुरोध कर रही हैं।',
    'referralTitle' => 'रोगी को विशेषज्ञ के पास भेजें',
    'selectSpecialist' => 'विशेषज्ञ चुनें',
    'referralNotes' => 'विशेषज्ञ के लिए नोट्स',
    'submitReferral' => 'रेफरल सबमिट करें',
    'liveConsultation' => 'लाइव परामर्श',
    'patientLanguage' => "रोगी की भाषा",
    'typeYourMessage' => 'अपना संदेश यहां टाइप करें...',
    'mentalHealthTitle' => 'मानसिक स्वास्थ्य जांच',
    'mentalHealthSubtitle' => 'आपके उत्तर गोपनीय हैं। यह हमें आपकी भलाई को समझने में मदद करता है।',
    'submitAnswers' => 'उत्तर सबमिट करें',
    'scoreInfo' => 'आपका स्क्रीनिंग स्कोर है',
    'scoreLow' => 'यह स्कोर एक स्वस्थ सीमा में है। अपना ख्याल रखते रहें!',
    'scoreMedium' => 'यह स्कोर बताता है कि आप कुछ भावनात्मक चुनौतियों का सामना कर रहे होंगे। किसी से बात करना मददगार हो सकता है। स्थानीय स्वास्थ्य क्लिनिक से संपर्क करने पर विचार करें।',
    'scoreHigh' => 'यह स्कोर इंगित करता है कि आप महत्वपूर्ण भावनात्मक संकट का सामना कर सकते हैं। यह अत्यधिक अनुशंसित है कि आप जल्द ही किसी डॉक्टर या मानसिक स्वास्थ्य पेशेवर से बात करें।',
    'rewardsTitle' => 'मेरे पुरस्कार',
    'yourPoints' => 'आपके अंक',
    'referFriend' => 'एक मित्र को रेफर करें',
    'howToEarn' => 'अंक कैसे अर्जित करें',
    'earnCheckup' => 'एक स्वास्थ्य जांच पूरी करें: +50 अंक',
    'earnReferral' => 'पंजीकरण करने वाले दूसरे कार्यकर्ता को रेफर करें: +100 अंक',
    'redeemPoints' => 'भविष्य के परामर्शों पर छूट के लिए अंक भुनाएं।',
    'esiStatus' => 'ईएसआई स्थिति',
    'esiLinkedTag' => 'लिंक किया गया',
    'esiNotLinkedTag' => 'लिंक नहीं है',
    'scanningTitle' => 'क्यूआर कोड स्कैन हो रहा है...',
    'scanningSubtitle' => 'कृपया क्यूआर कोड को स्थिर रखें।',
    'treatedPatients' => 'इलाज किए गए मरीज',
    'dengueFever' => 'डेंगू बुखार',
    'dengueDetails' => 'डेंगू एक वायरल संक्रमण है जो डेंगू वायरस (DENV) के कारण होता है, जो संक्रमित मच्छरों के काटने से मनुष्यों में फैलता है।',
    'denguePrecautions' => 'मच्छरों के काटने से बचें। ठहरा हुआ पानी हटाएं। लंबी आस्तीन पहनें। आराम करें और ओआरएस जैसे बहुत सारे तरल पदार्थ पिएं।',
    'denguePrescription' => 'बुखार के लिए, केवल पेरासिटामोल लें। एस्पिरिन या इबुप्रोफेन से बचें। तुरंत डॉक्टर से सलाह लें।',
    'malaria' => 'मलेरिया',
    'malariaDetails' => 'मलेरिया एक जानलेवा बीमारी है जो परजीवियों के कारण होती है जो संक्रमित मादा एनोफिलीज मच्छरों के काटने से लोगों में फैलती है।',
    'malariaPrecautions' => 'हमेशा मच्छरदानी के नीचे सोएं। मच्छर भगाने वाले का प्रयोग करें। ठंड लगने के साथ बुखार होने पर रक्त परीक्षण के लिए डॉक्टर को दिखाएं।',
    'malariaPrescription' => "डॉक्टर के परामर्श के बाद विशिष्ट मलेरिया-रोधी दवाओं की आवश्यकता होती है। स्व-दवा न करें।",
    'typhoid' => 'टाइफाइड बुखार',
    'typhoidDetails' => 'टाइफाइड बुखार एक गंभीर जीवाणु संक्रमण है जो दूषित भोजन, पानी और निकट संपर्क से आसानी से फैलता है।',
    'typhoidPrecautions' => 'केवल उबला हुआ या बोतलबंद पानी पिएं। अच्छी तरह से पका हुआ भोजन खाएं। बार-बार हाथ धोएं।',
    'typhoidPrescription' => 'डॉक्टर द्वारा निर्धारित एंटीबायोटिक दवाओं का एक कोर्स आवश्यक है। पूरा कोर्स पूरा करें।',
  ],
  'ml' => [
    'language' => 'മലയാളം',
    'selectLanguage' => 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    'loginTitle' => 'മൈഗ്രന്റ്‌കെയർ ലോഗിൻ',
    'mobilePlaceholder' => '10 അക്ക മൊബൈൽ നമ്പർ',
    'pinPlaceholder' => '4 അക്ക പിൻ',
    'loginButton' => 'ലോഗിൻ ചെയ്യുക',
    'registerPrompt' => 'അക്കൗണ്ട് ഇല്ലേ? രജിസ്റ്റർ ചെയ്യുക',
    'createAccountTitle' => 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    'enterMobileLabel' => 'മൊബൈൽ നമ്പർ നൽകുക',
    'sendOTPButton' => 'OTP അയയ്ക്കുക',
    'verifyOTPTitle' => 'OTP പരിശോധിക്കുക',
    'otpSentMessage' => '-ലേക്ക് ഒരു OTP അയച്ചു',
    'otpHint' => '(സൂചന: ഇത് 123456 ആണ്)',
    'otpPlaceholder' => '6 അക്ക OTP',
    'verifyOTPButton' => 'OTP പരിശോധിക്കുക',
    'setPinTitle' => 'നിങ്ങളുടെ പിൻ സജ്ജമാക്കുക',
    'createPinLabel' => '4 അക്ക പിൻ ഉണ്ടാക്കുക',
    'confirmPinLabel' => 'പിൻ ഉറപ്പിക്കുക',
    'createAccountButton' => 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    'alreadyHaveAccount' => 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ? ലോഗിൻ ചെയ്യുക',
    'selectRoleTitle' => 'നിങ്ങളുടെ പങ്ക് തിരഞ്ഞെടുക്കുക',
    'roleSelectionSubtitle' => 'ഈ ആപ്പ് നിങ്ങൾ എങ്ങനെ ഉപയോഗിക്കുമെന്ന് തിരഞ്ഞെടുക്കുക.',
    'workerRole' => 'ഞാൻ ഒരു തൊഴിലാളിയാണ്',
    'workerDescription' => 'നിങ്ങളുടെ ആരോഗ്യ രേഖകൾ ആക്‌സസ് ചെയ്യുകയും പരിചരണം കണ്ടെത്തുകയും ചെയ്യുക.',
    'doctorRole' => 'ഞാൻ ഒരു ഡോക്ടറാണ്',
    'doctorDescription' => 'രോഗിയുടെ രേഖകൾ നിയന്ത്രിക്കുകയും ആരോഗ്യ ഡാറ്റ കാണുക.',
    'welcomeMessage' => 'സ്വാഗതം,',
    'logout' => 'ലോഗൗട്ട്',
    'yourHealthID' => 'നിങ്ങളുടെ ഡിജിറ്റൽ ഹെൽത്ത് ഐഡി',
    'showQRCode' => 'ഈ ക്യുആർ കോഡ് ഏതെങ്കിലും ഡോക്ടറെയോ ക്ലിനിക്കിനെയോ കാണിക്കുക.',
    'viewMyHistory' => 'എന്റെ ആരോഗ്യ ചരിത്രം കാണുക',
    'findHospital' => 'ഒരു ആശുപത്രി കണ്ടെത്തുക',
    'healthAlerts' => 'ആരോഗ്യ മുന്നറിയിപ്പുകളും വിവരങ്ങളും',
    'patientLookup' => 'രോഗിയെ തിരയുക',
    'enterWorkerID' => 'ക്യുആർ കോഡിൽ നിന്ന് തൊഴിലാളി ഐഡി നൽകുക',
    'scanQRCode' => 'ക്യുആർ കോഡ് സ്കാൻ ചെയ്യുക',
    'viewPatientRecord' => 'രോഗിയുടെ റെക്കോർഡ് കാണുക',
    'publicHealthTitle' => 'പബ്ലിക് ഹെൽത്ത് ഇന്റലിജൻസ്',
    'publicHealthDescription' => 'തമിഴ്‌നാടിനായുള്ള തത്സമയ രോഗ നിരീക്ഷണ ഡാറ്റ കാണുക.',
    'viewDashboard' => 'ഡാഷ്‌ബോർഡ് കാണുക',
    'backToDashboard' => '< ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങുക',
    'workerProfileSetup' => 'തൊഴിലാളി പ്രൊഫൈൽ സജ്ജീകരണം',
    'fullNameLabel' => 'മുഴുവൻ പേര്',
    'ageLabel' => 'വയസ്സ്',
    'homeStateLabel' => 'സ്വന്തം സംസ്ഥാനം',
    'phoneNumberLabel' => 'ഫോൺ നമ്പർ',
    'emergencyContactLabel' => 'അടിയന്തര കോൺടാക്റ്റ് (ഓപ്ഷണൽ)',
    'currentLocationLabel' => 'നിലവിലെ സ്ഥലം',
    'getLocationButton' => 'സ്ഥലം നേടുക',
    'proceedToVerification' => 'പരിശോധനയിലേക്ക് പോകുക',
    'changeLanguage' => 'ഭാഷ മാറ്റുക',
    'labReports' => 'ലാബ് റിപ്പോർട്ടുകൾ',
    'testDate' => 'പരിശോധന തീയതി:',
    'at' => '-ൽ',
    'doctorsNotes' => "ഡോക്ടറുടെ കുറിപ്പുകൾ:",
    'viewReport' => 'റിപ്പോർട്ട് കാണുക',
    'healthProfileSetupTitle' => 'നിങ്ങളുടെ ആരോഗ്യ പ്രൊഫൈൽ പൂർത്തിയാക്കുക',
    'healthProfileSetupSubtitle' => 'ഈ ഐച്ഛിക ഘട്ടം ഡോക്ടർമാർക്ക് മികച്ച പരിചരണം നൽകാൻ സഹായിക്കുന്നു.',
    'heightLabel' => 'ഉയരം (സെന്റിമീറ്ററിൽ)',
    'weightLabel' => 'ഭാരം (കിലോയിൽ)',
    'bloodGroupLabel' => 'ബ്ലഡ് ഗ്രൂപ്പ്',
    'allergiesLabel' => 'നിങ്ങൾക്ക് എന്തെങ്കിലും അലർജിയുണ്ടോ? (ഉണ്ടെങ്കിൽ, വ്യക്തമാക്കുക)',
    'smokingLabel' => 'നിങ്ങൾ പുകവലിക്കുമോ?',
    'chronicDiseasesLabel' => 'മുൻകാല അല്ലെങ്കിൽ വിട്ടുമാറാത്ത രോഗങ്ങൾ പട്ടികപ്പെടുത്തുക',
    'yesOption' => 'അതെ',
    'noOption' => 'ഇല്ല',
    'preferNotToSayOption' => 'പറയാൻ താൽപ്പര്യമില്ല',
    'saveProfileButton' => 'പ്രൊഫൈൽ സംരക്ഷിക്കുക',
    'skipButton' => 'ഇപ്പോൾ ഒഴിവാക്കുക',
    'myHealthProfile' => 'എന്റെ ആരോഗ്യ പ്രൊഫൈൽ',
    'prescriptionReminders' => 'കുറിപ്പടി ഓർമ്മപ്പെടുത്തലുകൾ',
    'takeYourMedicineFor' => 'ഇതിനായി നിങ്ങളുടെ മരുന്ന് കഴിക്കുക',
    'prescribedByOn' => 'നിർദ്ദേശിച്ചത്',
    'searchBySymptom' => 'രോഗലക്ഷണം അല്ലെങ്കിൽ രോഗം ഉപയോഗിച്ച് തിരയുക...',
    'hotspotWarning' => 'ഉയർന്ന മുന്നറിയിപ്പ്: ഇത് നിലവിൽ നിങ്ങളുടെ പ്രദേശത്തെ ഒരു സജീവ ഹോട്ട്‌സ്‌പോട്ടാണ്.',
    'overviewTab' => 'അവലോകനം',
    'consultationsTab' => 'കൺസൾട്ടേഷനുകൾ',
    'vaccinesTab' => 'വാക്സിനുകൾ',
    'symptomChecker' => 'AI അസിസ്റ്റന്റ്',
    'firstAidGuide' => 'പ്രഥമശുശ്രൂഷാ ഗൈഡ്',
    'financialAid' => 'സാമ്പത്തിക സഹായം',
    'linkESICard' => 'ഇഎസ്ഐ കാർഡ് ലിങ്ക് ചെയ്യുക',
    'checkSymptoms' => 'രോഗലക്ഷണങ്ങൾ പരിശോധിക്കുക',
    'possibleConditions' => 'നിങ്ങളുടെ രോഗലക്ഷണങ്ങളെ അടിസ്ഥാനമാക്കി സാധ്യമായ അവസ്ഥകൾ',
    'selectSymptoms' => 'നിങ്ങളുടെ രോഗലക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക',
    'esiNumber' => 'ഇഎസ്ഐ കാർഡ് നമ്പർ',
    'linkCard' => 'കാർഡ് ലിങ്ക് ചെയ്യുക',
    'esiLinked' => 'ഇഎസ്ഐ കാർഡ് ലിങ്ക് ചെയ്തു',
    'aiWelcomeMessage' => 'നമസ്കാരം! ഞാൻ നിങ്ങളുടെ ആരോഗ്യ സഹായിയാണ്. ഇന്ന് നിങ്ങൾക്ക് എന്തു തോന്നുന്നു? നിങ്ങളുടെ രോഗലക്ഷണങ്ങൾ താഴെ വിവരിക്കുക.',
    'typeSymptomsHere' => 'നിങ്ങളുടെ രോഗലക്ഷണങ്ങൾ ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
    'mentalHealthScreening' => 'മാനസികാരോഗ്യ പരിശോധന',
    'consentForms' => 'സമ്മതപത്രങ്ങൾ',
    'referPatient' => 'രോഗിയെ റഫർ ചെയ്യുക',
    'startLiveChat' => 'ലൈവ് ചാറ്റ് ആരംഭിക്കുക',
    'digitalConsent' => 'ഡിജിറ്റൽ സമ്മതം',
    'consentStatus' => 'നില',
    'consentPending' => 'നിങ്ങളുടെ അംഗീകാരത്തിനായി കാത്തിരിക്കുന്നു',
    'consentGiven' => 'അംഗീകരിച്ചു',
    'approveConsent' => 'ഞാൻ സമ്മതിക്കുകയും സമ്മതം നൽകുകയും ചെയ്യുന്നു',
    'consentInfo' => 'ഡോ. പ്രിയ ശർമ്മ കൺസൾട്ടേഷൻ ആവശ്യങ്ങൾക്കായി നിങ്ങളുടെ പൂർണ്ണ ആരോഗ്യ ചരിത്രത്തിലേക്ക് പ്രവേശനം അഭ്യർത്ഥിക്കുന്നു.',
    'referralTitle' => 'രോഗിയെ സ്പെഷ്യലിസ്റ്റിലേക്ക് റഫർ ചെയ്യുക',
    'selectSpecialist' => 'സ്പെഷ്യലിസ്റ്റിനെ തിരഞ്ഞെടുക്കുക',
    'referralNotes' => 'സ്പെഷ്യലിസ്റ്റിനുള്ള കുറിപ്പുകൾ',
    'submitReferral' => 'റഫറൽ സമർപ്പിക്കുക',
    'liveConsultation' => 'ലൈവ് കൺസൾട്ടേഷൻ',
    'patientLanguage' => "രോഗിയുടെ ഭാഷ",
    'typeYourMessage' => 'നിങ്ങളുടെ സന്ദേശം ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
    'mentalHealthTitle' => 'മാനസികാരോഗ്യ പരിശോധന',
    'mentalHealthSubtitle' => 'നിങ്ങളുടെ ഉത്തരങ്ങൾ രഹസ്യാത്മകമാണ്. ഇത് നിങ്ങളുടെ ക്ഷേമം മനസ്സിലാക്കാൻ ഞങ്ങളെ സഹായിക്കുന്നു.',
    'submitAnswers' => 'ഉത്തരങ്ങൾ സമർപ്പിക്കുക',
    'scoreInfo' => 'നിങ്ങളുടെ സ്ക്രീനിംഗ് സ്കോർ ആണ്',
    'scoreLow' => 'ഈ സ്കോർ ആരോഗ്യകരമായ പരിധിയിലാണ്. സ്വയം ശ്രദ്ധിക്കുന്നത് തുടരുക!',
    'scoreMedium' => 'ഈ സ്കോർ നിങ്ങൾ ചില വൈകാരിക വെല്ലുവിളികൾ അനുഭവിക്കുന്നുണ്ടാകാമെന്ന് സൂചിപ്പിക്കുന്നു. ആരെയെങ്കിലും സംസാരിക്കുന്നത് സഹായകമാകും. ഒരു പ്രാദേശിക ആരോഗ്യ ക്ലിനിക്കുമായി ബന്ധപ്പെടുന്നത് പരിഗണിക്കുക.',
    'scoreHigh' => 'ഈ സ്കോർ നിങ്ങൾ കാര്യമായ വൈകാരിക ക്ലേശം നേരിടുന്നുണ്ടാകാമെന്ന് സൂചിപ്പിക്കുന്നു. നിങ്ങൾ ഉടൻ ഒരു ഡോക്ടറുമായോ മാനസികാരോഗ്യ പ്രൊഫഷണലുമായോ സംസാരിക്കുന്നത് വളരെ ഉചിതമാണ്.',
    'rewardsTitle' => 'എന്റെ റിവാർഡുകൾ',
    'yourPoints' => 'നിങ്ങളുടെ പോയിന്റുകൾ',
    'referFriend' => 'ഒരു സുഹൃത്തിനെ റഫർ ചെയ്യുക',
    'howToEarn' => 'പോയിന്റുകൾ എങ്ങനെ നേടാം',
    'earnCheckup' => 'ഒരു ആരോഗ്യ പരിശോധന പൂർത്തിയാക്കുക: +50 പോയിന്റുകൾ',
    'earnReferral' => 'രജിസ്റ്റർ ചെയ്യുന്ന മറ്റൊരു തൊഴിലാളിയെ റഫർ ചെയ്യുക: +100 പോയിന്റുകൾ',
    'redeemPoints' => 'ഭാവിയിലെ കൺസൾട്ടേഷനുകളിൽ കിഴിവുകൾക്കായി പോയിന്റുകൾ വീണ്ടെടുക്കുക.',
    'esiStatus' => 'ഇഎസ്ഐ നില',
    'esiLinkedTag' => 'ലിങ്ക് ചെയ്തു',
    'esiNotLinkedTag' => 'ലിങ്ക് ചെയ്തിട്ടില്ല',
    'scanningTitle' => 'ക്യുആർ കോഡ് സ്കാൻ ചെയ്യുന്നു...',
    'scanningSubtitle' => 'ദയവായി ക്യുആർ കോഡ് സ്ഥിരമായി പിടിക്കുക.',
    'treatedPatients' => 'ചികിത്സിച്ച രോഗികൾ',
    'dengueFever' => 'ഡെങ്കിപ്പനി',
    'dengueDetails' => 'ഡെങ്കി വൈറസ് (DENV) മൂലമുണ്ടാകുന്ന ഒരു വൈറൽ അണുബാധയാണ് ഡെങ്കിപ്പനി, ഇത് രോഗബാധിതരായ കൊതുകുകളുടെ കടിയിലൂടെ മനുഷ്യരിലേക്ക് പകരുന്നു.',
    'denguePrecautions' => 'കൊതുകുകടി ഒഴിവാക്കുക. കെട്ടിക്കിടക്കുന്ന വെള്ളം നീക്കം ചെയ്യുക. നീണ്ട കൈകളുള്ള വസ്ത്രം ധരിക്കുക. വിശ്രമിക്കുകയും ഒആർഎസ് പോലുള്ള ധാരാളം ദ്രാവകങ്ങൾ കുടിക്കുകയും ചെയ്യുക.',
    'denguePrescription' => 'പനിക്ക്, പാരസെറ്റമോൾ മാത്രം കഴിക്കുക. ആസ്പിരിൻ അല്ലെങ്കിൽ ഐബുപ്രോഫെൻ ഒഴിവാക്കുക. ഉടൻ ഒരു ഡോക്ടറെ സമീപിക്കുക.',
    'malaria' => 'മലേറിയ',
    'malariaDetails' => 'രോഗബാധിതരായ പെൺ അനോഫിലിസ് കൊതുകുകളുടെ കടിയിലൂടെ മനുഷ്യരിലേക്ക് പകരുന്ന പരാന്നഭോജികൾ മൂലമുണ്ടാകുന്ന ഒരു ജീവൻ അപകടപ്പെടുത്തുന്ന രോഗമാണ് മലേറിയ.',
    'malariaPrecautions' => 'എല്ലായ്പ്പോഴും കൊതുകുവലയ്ക്കുള്ളിൽ ഉറങ്ങുക. കൊതുക് നാശിനി ഉപയോഗിക്കുക. വിറയലോടെ പനിയുണ്ടെങ്കിൽ രക്തപരിശോധനയ്ക്കായി ഒരു ഡോക്ടറെ കാണുക.',
    'malariaPrescription' => "ഒരു ഡോക്ടറുടെ കൺസൾട്ടേഷനുശേഷം പ്രത്യേക മലേറിയ വിരുദ്ധ മരുന്നുകൾ ആവശ്യമാണ്. സ്വയം ചികിത്സിക്കരുത്.",
    'typhoid' => 'ടൈഫോയ്ഡ് പനി',
    'typhoidDetails' => 'ടൈഫോയ്ഡ് പനി ഒരു ഗുരുതരമായ ബാക്ടീരിയ അണുബാധയാണ്, ഇത് മലിനമായ ഭക്ഷണം, വെള്ളം, അടുത്ത സമ്പർക്കം എന്നിവയിലൂടെ എളുപ്പത്തിൽ പടരുന്നു.',
    'typhoidPrecautions' => 'തിളപ്പിച്ചതോ കുപ്പിവെള്ളമോ മാത്രം കുടിക്കുക. നന്നായി പാകം ചെയ്ത ഭക്ഷണം കഴിക്കുക. ഇടയ്ക്കിടെ കൈകൾ കഴുകുക.',
    'typhoidPrescription' => 'ഒരു ഡോക്ടർ നിർദ്ദേശിക്കുന്ന ആൻറിബയോട്ടിക്കുകളുടെ ഒരു കോഴ്സ് ആവശ്യമാണ്. പൂർണ്ണമായ കോഴ്സ് പൂർത്തിയാക്കുക.',
  ],
  'te' => [
    'language' => 'తెలుగు',
    'selectLanguage' => 'మీ భాషను ఎంచుకోండి',
    'loginTitle' => 'మైగ్రెంట్‌కేర్ లాగిన్',
    'mobilePlaceholder' => '10-అంకెల మొబైల్ నంబర్',
    'pinPlaceholder' => '4-అంకెల పిన్',
    'loginButton' => 'లాగిన్ చేయండి',
    'registerPrompt' => 'ఖాతా లేదా? నమోదు చేసుకోండి',
    'createAccountTitle' => 'ఖాతాను సృష్టించండి',
    'enterMobileLabel' => 'మొబైల్ నంబర్ నమోదు చేయండి',
    'sendOTPButton' => 'OTP పంపండి',
    'verifyOTPTitle' => 'OTPని ధృవీకరించండి',
    'otpSentMessage' => '-కి ఒక OTP పంపబడింది',
    'otpHint' => '(సూచన: ఇది 123456)',
    'otpPlaceholder' => '6-అంకెల OTP',
    'verifyOTPButton' => 'OTPని ధృవీకరించండి',
    'setPinTitle' => 'మీ పిన్‌ను సెట్ చేయండి',
    'createPinLabel' => '4-అంకెల పిన్‌ను సృష్టించండి',
    'confirmPinLabel' => 'పిన్‌ను నిర్ధారించండి',
    'createAccountButton' => 'ఖాతాను సృష్టించండి',
    'alreadyHaveAccount' => 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ చేయండి',
    'selectRoleTitle' => 'మీ పాత్రను ఎంచుకోండి',
    'roleSelectionSubtitle' => 'దయచేసి మీరు ఈ యాప్‌ను ఎలా ఉపయోగిస్తారో ఎంచుకోండి.',
    'workerRole' => 'నేను కార్మికుడిని',
    'workerDescription' => 'మీ ఆరోగ్య రికార్డులను యాక్సెస్ చేయండి మరియు సంరక్షణను కనుగొనండి.',
    'doctorRole' => 'నేను వైద్యుడిని',
    'doctorDescription' => 'రోగి రికార్డులను నిర్వహించండి మరియు ఆరోగ్య డేటాను వీక్షించండి.',
    'welcomeMessage' => 'స్వాగతం,',
    'logout' => 'లాగ్ అవుట్',
    'yourHealthID' => 'మీ డిజిటల్ హెల్త్ ఐడి',
    'showQRCode' => 'ఈ క్యూఆర్ కోడ్‌ను ఏదైనా డాక్టర్ లేదా క్లినిక్‌కు చూపండి.',
    'viewMyHistory' => 'నా ఆరోగ్య చరిత్రను వీక్షించండి',
    'findHospital' => 'ఆసుపత్రిని కనుగొనండి',
    'healthAlerts' => 'ఆరోగ్య హెచ్చరికలు & సమాచారం',
    'patientLookup' => 'రోగి శోధన',
    'enterWorkerID' => 'క్యూఆర్ కోడ్ నుండి కార్మికుడి ఐడిని నమోదు చేయండి',
    'scanQRCode' => 'క్యూఆర్ కోడ్‌ను స్కాన్ చేయండి',
    'viewPatientRecord' => 'రోగి రికార్డును వీక్షించండి',
    'publicHealthTitle' => 'ప్రజారోగ్య ఇంటెలిజెన్స్',
    'publicHealthDescription' => 'తమిళనాడుకు సంబంధించిన వాస్తవ-సమయ వ్యాధి నిఘా డేటాను వీక్షించండి.',
    'viewDashboard' => 'డాష్‌బోర్డ్‌ను వీక్షించండి',
    'backToDashboard' => '< డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళు',
    'workerProfileSetup' => 'కార్మికుడి ప్రొఫైల్ సెటప్',
    'fullNameLabel' => 'పూర్తి పేరు',
    'ageLabel' => 'వయస్సు',
    'homeStateLabel' => 'సొంత రాష్ట్రం',
    'phoneNumberLabel' => 'ఫోను నంబరు',
    'emergencyContactLabel' => 'అత్యవసర సంప్రదింపు (ఐచ్ఛికం)',
    'currentLocationLabel' => 'ప్రస్తుత ప్రదేశం',
    'getLocationButton' => 'ప్రదేశాన్ని పొందండి',
    'proceedToVerification' => 'ధృవీకరణకు కొనసాగండి',
    'changeLanguage' => 'భాషను మార్చండి',
    'labReports' => 'ల్యాబ్ నివేదికలు',
    'testDate' => 'పరీక్ష తేదీ:',
    'at' => '-లో',
    'doctorsNotes' => "డాక్టర్ గమనికలు:",
    'viewReport' => 'నివేదికను వీక్షించండి',
    'healthProfileSetupTitle' => 'మీ ఆరోగ్య ప్రొఫైల్‌ను పూర్తి చేయండి',
    'healthProfileSetupSubtitle' => 'ఈ ఐచ్ఛిక దశ వైద్యులకు మెరుగైన సంరక్షణ అందించడంలో సహాయపడుతుంది.',
    'heightLabel' => 'ఎత్తు (సెం.మీ.లో)',
    'weightLabel' => 'బరువు (కిలోలలో)',
    'bloodGroupLabel' => 'రక్త వర్గం',
    'allergiesLabel' => 'మీకు ఏమైనా అలెర్జీలు ఉన్నాయా? (ఉంటే, పేర్కొనండి)',
    'smokingLabel' => 'మీరు ధూమపానం చేస్తారా?',
    'chronicDiseasesLabel' => 'ఏవైనా గత లేదా దీర్ఘకాలిక వ్యాధులను జాబితా చేయండి',
    'yesOption' => 'అవును',
    'noOption' => 'కాదు',
    'preferNotToSayOption' => 'చెప్పడానికి ఇష్టపడను',
    'saveProfileButton' => 'ప్రొఫైల్‌ను సేవ్ చేయండి',
    'skipButton' => 'ఇప్పటికి దాటవేయి',
    'myHealthProfile' => 'నా ఆరోగ్య ప్రొఫైల్',
    'prescriptionReminders' => 'ప్రిస్క్రిప్షన్ రిమైండర్‌లు',
    'takeYourMedicineFor' => 'దీని కోసం మీ మందు తీసుకోండి',
    'prescribedByOn' => 'సూచించిన వారు',
    'searchBySymptom' => 'లక్షణం లేదా వ్యాధి ద్వారా శోధించండి...',
    'hotspotWarning' => 'అధిక హెచ్చరిక: ఇది ప్రస్తుతం మీ ప్రాంతంలో చురుకైన హాట్‌స్పాట్.',
    'overviewTab' => 'అవలోకనం',
    'consultationsTab' => 'సంప్రదింపులు',
    'vaccinesTab' => 'టీకాలు',
    'symptomChecker' => 'AI సహాయకుడు',
    'firstAidGuide' => 'ప్రథమ చికిత్స గైడ్',
    'financialAid' => 'ఆర్థిక సహాయం',
    'linkESICard' => 'ESI కార్డును లింక్ చేయండి',
    'checkSymptoms' => 'లక్షణాలను తనిఖీ చేయండి',
    'possibleConditions' => 'మీ లక్షణాల ఆధారంగా సాధ్యమయ్యే పరిస్థితులు',
    'selectSymptoms' => 'మీ లక్షణాలను ఎంచుకోండి',
    'esiNumber' => 'ESI కార్డు నంబర్',
    'linkCard' => 'కార్డును లింక్ చేయండి',
    'esiLinked' => 'ESI కార్డు లింక్ చేయబడింది',
    'aiWelcomeMessage' => 'నమస్కారం! నేను మీ ఆరోగ్య సహాయకుడిని. ఈ రోజు మీరు ఎలా ఉన్నారు? మీ లక్షణాలను క్రింద వివరించండి.',
    'typeSymptomsHere' => 'మీ లక్షణాలను ఇక్కడ టైప్ చేయండి...',
    'mentalHealthScreening' => 'మానసిక ఆరోగ్య స్క్రీనింగ్',
    'consentForms' => 'సమ్మతి పత్రాలు',
    'referPatient' => 'రోగిని giới thiệu చేయండి',
    'startLiveChat' => 'ప్రత్యక్ష చాట్ ప్రారంభించండి',
    'digitalConsent' => 'డిజిటల్ సమ్మతి',
    'consentStatus' => 'స్థితి',
    'consentPending' => 'మీ ఆమోదం కోసం పెండింగ్‌లో ఉంది',
    'consentGiven' => 'ఆమోదించబడింది',
    'approveConsent' => 'నేను అంగీకరించి సమ్మతి ఇస్తున్నాను',
    'consentInfo' => 'డాక్టర్ ప్రియా శర్మ సంప్రదింపుల ప్రయోజనాల కోసం మీ పూర్తి ఆరోగ్య చరిత్రకు ప్రాప్యతను అభ్యర్థిస్తున్నారు.',
    'referralTitle' => 'రోగిని నిపుణుడికి giới thiệu చేయండి',
    'selectSpecialist' => 'నిపుణుడిని ఎంచుకోండి',
    'referralNotes' => 'నిపుణుడి కోసం గమనికలు',
    'submitReferral' => 'రిఫరల్‌ను సమర్పించండి',
    'liveConsultation' => 'ప్రత్యక్ష సంప్రదింపు',
    'patientLanguage' => "రోగి భాష",
    'typeYourMessage' => 'మీ సందేశాన్ని ఇక్కడ టైప్ చేయండి...',
    'mentalHealthTitle' => 'మానసిక ఆరోగ్య తనిఖీ',
    'mentalHealthSubtitle' => 'మీ సమాధానాలు గోప్యంగా ఉంచబడతాయి. ఇది మీ శ్రేయస్సును అర్థం చేసుకోవడానికి మాకు సహాయపడుతుంది.',
    'submitAnswers' => 'సమాధానాలను సమర్పించండి',
    'scoreInfo' => 'మీ స్క్రీనింగ్ స్కోరు',
    'scoreLow' => 'ఈ స్కోరు ఆరోగ్యకరమైన పరిధిలో ఉంది. మిమ్మల్ని మీరు జాగ్రత్తగా చూసుకోండి!',
    'scoreMedium' => 'ఈ స్కోరు మీరు కొన్ని భావోద్వేగ సవాళ్లను ఎదుర్కొంటున్నారని సూచిస్తుంది. ఎవరితోనైనా మాట్లాడటం సహాయకరంగా ఉంటుంది. స్థానిక ఆరోగ్య క్లినిక్‌ను సంప్రదించడం పరిగణించండి.',
    'scoreHigh' => 'ఈ స్కోరు మీరు గణనీయమైన భావోద్వేగ క్షోభను ఎదుర్కొంటున్నారని సూచిస్తుంది. మీరు త్వరలో ఒక వైద్యుడు లేదా మానసిక ఆరోగ్య నిపుణుడితో మాట్లాడటం చాలా సిఫార్సు చేయబడింది.',
    'rewardsTitle' => 'నా బహుమతులు',
    'yourPoints' => 'మీ పాయింట్లు',
    'referFriend' => 'స్నేహితుడిని giới thiệu చేయండి',
    'howToEarn' => 'పాయింట్లను ఎలా సంపాదించాలి',
    'earnCheckup' => 'ఆరోగ్య తనిఖీని పూర్తి చేయండి: +50 పాయింట్లు',
    'earnReferral' => 'నమోదు చేసుకున్న మరో కార్మికుడిని giới thiệu చేయండి: +100 పాయింట్లు',
    'redeemPoints' => 'భవిష్యత్ సంప్రదింపులపై తగ్గింపుల కోసం పాయింట్లను రీడీమ్ చేసుకోండి.',
    'esiStatus' => 'ESI స్థితి',
    'esiLinkedTag' => 'లింక్ చేయబడింది',
    'esiNotLinkedTag' => 'లింక్ చేయబడలేదు',
    'scanningTitle' => 'క్యూఆర్ కోడ్‌ను స్కాన్ చేస్తోంది...',
    'scanningSubtitle' => 'దయచేసి క్యూఆర్ కోడ్‌ను స్థిరంగా పట్టుకోండి.',
    'treatedPatients' => 'చికిత్స పొందిన రోగులు',
    'dengueFever' => 'డెంగ్యూ జ్వరం',
    'dengueDetails' => 'డెంగ్యూ అనేది డెంగ్యూ వైరస్ (DENV) వల్ల కలిగే వైరల్ ఇన్ఫెక్షన్, ఇది సోకిన దోమల కాటు ద్వారా మానవులకు వ్యాపిస్తుంది.',
    'denguePrecautions' => 'దోమ కాటును నివారించండి. నిలిచిన నీటిని తొలగించండి. పొడవాటి చేతుల దుస్తులు ధరించండి. విశ్రాంతి తీసుకోండి మరియు ఓఆర్ఎస్ వంటి ద్రవాలు పుష్కలంగా త్రాగండి.',
    'denguePrescription' => 'జ్వరం కోసం, పారాసిటమాల్ మాత్రమే తీసుకోండి. ఆస్పిరిన్ లేదా ఇబుప్రోఫెన్‌ను నివారించండి. వెంటనే వైద్యుడిని సంప్రదించండి.',
    'malaria' => 'మలేరియా',
    'malariaDetails' => 'మలేరియా అనేది పరాన్నజీవుల వల్ల కలిగే ప్రాణాంతక వ్యాధి, ఇది సోకిన ఆడ అనాఫిలిస్ దోమల కాటు ద్వారా ప్రజలకు వ్యాపిస్తుంది.',
    'malariaPrecautions' => 'ఎల్లప్పుడూ దోమతెర కింద నిద్రించండి. దోమల నివారణ మందును ఉపయోగించండి. చలితో కూడిన జ్వరం ఉంటే రక్త పరీక్ష కోసం వైద్యుడిని చూడండి.',
    'malariaPrescription' => "వైద్యుడి సంప్రదింపుల తర్వాత నిర్దిష్ట మలేరియా నిరోధక మందులు అవసరం. స్వీయ-వైద్యం చేయవద్దు.",
    'typhoid' => 'టైఫాయిడ్ జ్వరం',
    'typhoidDetails' => 'టైఫాయిడ్ జ్వరం ఒక తీవ్రమైన బాక్టీరియల్ ఇన్ఫెక్షన్, ఇది కలుషితమైన ఆహారం, నీరు మరియు సన్నిహిత పరిచయం ద్వారా సులభంగా వ్యాపిస్తుంది.',
    'typhoidPrecautions' => 'కాచిన లేదా సీసాల్లోని నీటిని మాత్రమే త్రాగండి. బాగా ఉడికిన ఆహారాన్ని తినండి. తరచుగా చేతులు కడుక్కోండి.',
    'typhoidPrescription' => 'వైద్యుడు సూచించిన యాంటీబయాటిక్స్ కోర్సు అవసరం. పూర్తి కోర్సును పూర్తి చేయండి.',
  ]
];

function t($key) {
    global $translations;
    $lang = $_SESSION['language'] ?? 'en';
    return $translations[$lang][$key] ?? ($translations['en'][$key] ?? $key);
}

function isLoggedIn() { return isset($_SESSION['user_id']); }
function requireLogin() { if (!isLoggedIn()) { header('Location: index.php?page=login'); exit(); } }
function getWorker($conn, $userId) {
    $stmt = $conn->prepare("SELECT * FROM workers WHERE userId = ?");
    $stmt->bind_param("i", $userId);
    $stmt->execute();
    return $stmt->get_result()->fetch_assoc();
}
function getDoctor($conn, $userId) {
    $stmt = $conn->prepare("SELECT * FROM doctors WHERE userId = ?");
    $stmt->bind_param("i", $userId);
    $stmt->execute();
    return $stmt->get_result()->fetch_assoc();
}

// ## UPDATED FUNCTION TO CALL THE GOOGLE AI (GEMINI) MODEL ##
function getSymptomsFromAI($userInput) {
    $apiKey = "AIzaSyDiwHoQKqZRaMBG2C5rKhEZkF9A_gwvGEo"; 

    // ** FINAL CHANGE: Using the confirmed 'gemini-2.5-pro' model name **
    $apiUrl = "https://generativelanguage.googleapis.com/v1/models/gemini-2.5-pro:generateContent?key=" . $apiKey;
    
    // A detailed prompt for the AI to extract symptoms accurately
    $prompt = "You are a helpful medical symptom identifier. Analyze the user's text and extract a list of medical symptoms.
    Rules:
    - Only identify common, single or two-word symptoms.
    - If you find symptoms, return them as a JSON array of strings. Example: [\"fever\", \"headache\", \"sore throat\"]
    - If the user is just greeting you (e.g., 'hello', 'hi') or no symptoms are mentioned, return an empty JSON array: []
    User's Text: \"{$userInput}\"";

    $data = [
        'contents' => [
            [
                'parts' => [
                    ['text' => $prompt]
                ]
            ]
        ],
        'safetySettings' => [
            [ 'category' => 'HARM_CATEGORY_HARASSMENT', 'threshold' => 'BLOCK_NONE' ],
            [ 'category' => 'HARM_CATEGORY_HATE_SPEECH', 'threshold' => 'BLOCK_NONE' ],
            [ 'category' => 'HARM_CATEGORY_SEXUALLY_EXPLICIT', 'threshold' => 'BLOCK_NONE' ],
            [ 'category' => 'HARM_CATEGORY_DANGEROUS_CONTENT', 'threshold' => 'BLOCK_NONE' ]
        ]
    ];
    $jsonData = json_encode($data);

    $ch = curl_init($apiUrl);
    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $error = curl_error($ch);
    curl_close($ch);

    if ($httpCode !== 200) {
        $logMessage = "AI API Error! HTTP Code: {$httpCode}. cURL Error: {$error}. Response: {$response}\n";
        error_log($logMessage);
        return null; // Return null on failure
    }

    $result = json_decode($response, true);
    $rawText = $result['candidates'][0]['content']['parts'][0]['text'] ?? '[]';
    $cleanedText = preg_replace('/```json\s*|\s*```/', '', $rawText);
    $symptoms = json_decode(trim($cleanedText), true);
    
    return is_array($symptoms) ? $symptoms : [];
}
function getAIChatResponse($userInput) {
    // ---
    // SECURITY NOTE: It's safer to store your API key outside the code,
    // for example, in an environment variable or a separate config file.
    // ---
    $apiKey = "AIzaSyDiwHoQKqZRaMBG2C5rKhEZkF9A_gwvGEo"; // Using the same key as your other function
    $apiUrl = "https://generativelanguage.googleapis.com/v1/models/gemini-2.5-pro:generateContent?key=" . $apiKey;

    // This is the system prompt that defines the AI's persona and rules
    $systemPrompt = "You are a friendly and empathetic health assistant. Your goal is to provide helpful, general information and support. 
    **Disclaimer: You are an AI assistant, not a medical professional. Your advice should not be taken as a substitute for professional medical advice. Always consult with a qualified healthcare provider for any health concerns.**
    
    Keep your answers concise and easy to understand for a non-medical person.
    If the user asks for a diagnosis, gently decline and remind them to see a doctor.
    If the user describes symptoms, you can provide general information about possible causes and home care, but always end by recommending a professional consultation.";

    // We combine the system prompt and the user's message
    $fullPrompt = $systemPrompt . "\n\nUSER'S MESSAGE:\n\"" . $userInput . "\"\n\nAI ASSISTANT'S RESPONSE:";

    $data = [
        'contents' => [
            [
                'parts' => [
                    ['text' => $fullPrompt]
                ]
            ]
        ],
        'safetySettings' => [
            [ 'category' => 'HARM_CATEGORY_HARASSMENT', 'threshold' => 'BLOCK_NONE' ],
            [ 'category' => 'HARM_CATEGORY_HATE_SPEECH', 'threshold' => 'BLOCK_NONE' ],
            [ 'category' => 'HARM_CATEGORY_SEXUALLY_EXPLICIT', 'threshold' => 'BLOCK_NONE' ],
            [ 'category' => 'HARM_CATEGORY_DANGEROUS_CONTENT', 'threshold' => 'BLOCK_NONE' ]
        ]
    ];
    $jsonData = json_encode($data);

    $ch = curl_init($apiUrl);
    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $error = curl_error($ch);
    curl_close($ch);

    if ($httpCode !== 200) {
        $logMessage = "AI Chat Error! HTTP Code: {$httpCode}. cURL Error: {$error}. Response: {$response}\n";
        error_log($logMessage);
        return "I'm sorry, I'm having trouble connecting right now. Please try again later.";
    }

    $result = json_decode($response, true);
    
    // Check for safety blocks or empty response
    if (empty($result['candidates'])) {
         if (isset($result['promptFeedback']['blockReason'])) {
            error_log("AI Chat Blocked: " . $result['promptFeedback']['blockReason']);
            return "I'm sorry, I can't respond to that topic. Please try asking something else.";
         }
        return "I'm sorry, I didn't get a valid response. Please try again.";
    }

    // Get the actual text reply
    $aiText = $result['candidates'][0]['content']['parts'][0]['text'] ?? "I'm sorry, I couldn't process that. Please try again.";
    
    return $aiText;
}


?>